FROM ruby:latest
RUN apt-get -y update && apt-get -y install libicu-dev cmake && rm -rf /var/lib/apt/lists/*
RUN gem install github-linguist gollum github-markdown
RUN gem install gollum
RUN gem install github-markdown
#RUN gem install org-ruby
VOLUME /srv/web/wiki
WORKDIR /srv/web
RUN cd wiki && git init
ENTRYPOINT ["gollum", "--port", "80", "--user-icons", "--live-preview", "gravatar", "--h1-title", "--collapse-tree", "/wiki"]
EXPOSE 80
